version: "3.7"

services:
  database_foodfy:
    image: postgres
    container_name: database_foodfy
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=foodfy
      - POSTGRES_DB=foodfy
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: foodfy
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_foodfy
    depends_on:
      - database_foodfy


volumes: 
  pgdata:
    driver: local